version: '3'

services:
   
  api:
    restart: always
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    networks:
      - redis-net
    depends_on:
      - redis
    ports:
      - "8000:8000"
    volumes:
      - api_data:/docker_api
      - jenkins_data:/var/jenkins_home
      - .:/code
    depends_on:
      - db
    tty: true
    
  redis:
    image: redis:4.0.6-alpine
    hostname: redis
    networks:
      - redis-net
    volumes:
      - redis-data:/data

  jenkins:
    build: ./jenkins
    restart: always
    ports:
        - "8080:8080"
        - "50000:50000"
    volumes:
        - ./workspace/workspace/demo/api:/docker_api
    

networks:
  redis-net:

volumes:
  redis-data:
     driver: local 
  api_data:
  jenkins_data:
  pgdata_jenkins:

    


