# Generated by Django 2.0.4 on 2018-04-29 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='filmes',
            new_name='filme',
        ),
    ]
