# Generated by Django 2.0.4 on 2018-04-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0003_auto_20180429_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='filmes',
            new_name='filme',
        ),
        migrations.AlterField(
            model_name='filme',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
