# Generated by Django 2.0.4 on 2018-04-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0004_auto_20180429_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
