# Generated by Django 2.0.4 on 2018-04-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0005_filme_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
